#! /bin/sh
export VISUAL="micro"
xsetroot -cursor_name left_ptr &
compton &
pulseaudio &
insync start &
sxhkd &
nm-applet --sm-disable &
date >> bspwm.log
setxkbmap de
sxhkd &

bspc monitor eDP1 -d 1 2 3 4 5 6 7
bspc monitor HDMI1 -d 8

# Visual options
bspc config click_to_focus any
bspc config border_width         3
bspc config window_gap          0
bspc config top_padding 		25
bspc config bottom_padding 		25

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false


# Rules
bspc rule -a jetbrains-toolbox state=floating
bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a guake state=floating
bspc rule -a Firefox desktop='^2'
bspc rule -a KeePass desktop='^6'
bspc rule -a Thunderbird desktop='^3'
bspc rule -a chromium desktop='^2'
bspc rule -a Hexchat desktop='^7'
bspc rule -a Slack desktop='^7'
bspc rule -a Pidgin desktop='^7'
bspc rule -a telegram-desktop desktop='^7'
bspc rule -a vlc state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Colers
hsetroot -full ~/Bilder/Wallpapers/solarized-wallpaper-kernel.png
# create light blue conky 
conky -c ~/.conkyrc &

bspc config normal_border_color "#333333"
bspc config focused_border_color "#2d8bcb"      #linecolor from polybar

# create bar in light blue
dunst -config ~/.config/polybar/themes/ColorFull/dunst/dunst-lightblue >> /home/alex/.dunst.log &
# chek if gnome session integration is running. I set the env-var "Gsession = true" if gnome session integration is running.
if [ "$(printenv Gsession)" = true ]
	then
	polybar -c ~/.config/polybar/themes/tetris/config.g main &
	else
	polybar -c ~/.config/polybar/themes/tetris/config main &
fi
polybar -c ~/.config/polybar/themes/tetris/config bottom &

# mopidy as mpd server
mopidy &