#! /bin/sh

sxhkd &

bspc monitor eDP1 -d 1 2 3 4 5 6 7
bspc monitor HDMI1 -d 8

# Visual options
bspc config click_to_focus any
bspc config border_width         2
bspc config window_gap          12
bspc config top_padding 		17 
bspc config bottom_padding 		12 

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false


# Rules
bspc rule -a Gimp desktop='^7' state=floating follow=on
#bspc rule -a feh state=floating
bspc rule -a Firefox desktop='^2'
bspc rule -a Thunderbird desktop='^3'
bspc rule -a chromium desktop='^2'
bspc rule -a Hexchat desktop='^7'
bspc rule -a Pidgin desktop='^7'
bspc rule -a Telegram desktop='^7'
bspc rule -a ./telegram/Telegram desktop='^7'
bspc rule -a vlc state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

polybar -c ~/.config/polybar/themes/darkpx/polybar top -q > /dev/null &


# Colers
hsetroot -full ~/Bilder/Wallpapers/1.png
bspc config normal_border_color "#333333"       
bspc config focused_border_color "#7B0000"      
